# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20170828_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ticket',
            field=models.PositiveIntegerField(verbose_name='\u0411\u0456\u043b\u0435\u0442'),
        ),
    ]
