# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20170904_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u0456\u0441\u043f\u0438\u0442\u0443')),
                ('date', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0456\u0441\u043f\u0438\u0442\u0443')),
                ('teacher', models.CharField(max_length=255, verbose_name='\u0412\u0438\u043a\u043b\u0430\u0434\u0430\u0447')),
                ('testing_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Group', verbose_name='\u0413\u0440\u0443\u043f\u0430 \u0434\u043e \u0456\u0441\u043f\u0438\u0442\u0443')),
            ],
            options={
                'verbose_name': '\u0406\u0441\u043f\u0438\u0442',
                'verbose_name_plural': '\u0406\u0441\u043f\u0438\u0442\u0438',
            },
        ),
    ]
